spring:
  datasource:
    url: jdbc:mysql://47.103.149.168:3306/star?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: GUaidonggua
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 1
    host: 47.103.149.168
    port: 6379
    password: Guaidonggua
server:
  port: 8888
  servlet:
    context-path: /api